FROM debian:bookworm

COPY . /usr/local/src/helloart
RUN apt-get update && \
	apt-get -y install \
		debhelper \
		dh-python \
		dh-virtualenv \
		dpkg-dev \
		make \
		python3-dev \
		python3-venv \
		python-is-python3 \
		python3-setuptools
WORKDIR /usr/local/src/helloart
RUN dpkg-buildpackage -uc -us -b
#RUN make build
